#!/usr/bin/env python3
"""Derive the fork change list (A/B/C/D/U spine) from git objects.

Beads: project-rkk9 (derivation), project-iylw (consumer via classify()).
Never hand-edit the outputs: manifest/CHANGES.md (human) and
drift/fork-spine.json (machine, read by scripts/gen_coverage.py).

Classes (filenames in bin/):
  A  fork-only:               in fork HEAD, absent at merge-base
  B  upstream-only:           in upstream, absent in fork HEAD
  C  converged:               differs from base, identical fork == upstream
  D  real delta:              present in base+fork+upstream, fork != upstream
  U  modified, absent upstream: in fork+base, changed on fork, deleted upstream

Revs: --base defaults to the fork/upstream merge-base (must resolve in the
fork object store); --fork-rev defaults to the served fork HEAD; --upstream
defaults to sources/firstmate at its pinned gitlink.

State column (falsifiable enum): ported | delta-carried | refused |
not-porting. v1 defaults every row to not-porting; the port workflow flips
rows with manifest linkage. Intent lives in beads/manifest, never here.

Usage:
  python3 scripts/gen_fork_spine.py [--check] [--fork PATH] [--upstream PATH]
  --check verifies the committed spine matches a fresh derivation.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHANGES_MD = ROOT / "manifest" / "CHANGES.md"
SPINE_JSON = ROOT / "drift" / "fork-spine.json"
DEFAULT_FORK = Path.home() / "code" / "firstmate"


def sh(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, check=True
    )


def ls_bin(repo: Path, rev: str) -> list[str]:
    out = sh(repo, "ls-tree", "-r", "--name-only", rev, "--", "bin/").stdout.decode()
    return sorted(p.removeprefix("bin/") for p in out.split() if p.startswith("bin/"))


def blob(repo: Path, rev: str, name: str) -> bytes | None:
    r = subprocess.run(
        ["git", "-C", str(repo), "show", f"{rev}:bin/{name}"],
        capture_output=True,
    )
    return r.stdout if r.returncode == 0 else None


def sha(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()[:12]


def derive(fork: Path, fork_rev: str, upstream: Path, up_rev: str,
           base: str) -> list[dict]:
    base_files = set(ls_bin(fork, base))
    fork_files = set(ls_bin(fork, fork_rev))
    up_files = set(ls_bin(upstream, up_rev))
    rows: list[dict] = []
    for name in sorted(fork_files - base_files):
        fb = blob(fork, fork_rev, name) or b""
        rows.append({"surface": name, "class": "A",
                     "fork_rev": fork_rev[:12], "fork_hash": sha(fb),
                     "upstream_hash": None, "state": "not-porting"})
    for name in sorted(up_files - fork_files):
        ub = blob(upstream, up_rev, name) or b""
        rows.append({"surface": name, "class": "B",
                     "fork_rev": None, "fork_hash": None,
                     "upstream_hash": sha(ub), "state": "not-porting"})
    for name in sorted(fork_files & base_files & up_files):
        fb, ub, bb = (blob(fork, fork_rev, name),
                      blob(upstream, up_rev, name),
                      blob(fork, base, name))
        if fb == ub == bb:
            continue
        cls = "C" if fb == ub else "D"
        rows.append({"surface": name, "class": cls,
                     "fork_rev": fork_rev[:12], "fork_hash": sha(fb or b""),
                     "upstream_hash": sha(ub or b""), "state": "not-porting"})
    for name in sorted((fork_files & base_files) - up_files):
        fb, bb = blob(fork, fork_rev, name), blob(fork, base, name)
        if fb != bb:
            rows.append({"surface": name, "class": "U",
                         "fork_rev": fork_rev[:12], "fork_hash": sha(fb or b""),
                         "upstream_hash": None, "state": "not-porting"})
    return rows


def render_md(rows: list[dict], base: str, fork_rev: str, up_rev: str) -> str:
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["class"]] = counts.get(r["class"], 0) + 1
    lines = [
        "# Fork change list (generated spine)",
        "",
        "<!-- GENERATED by scripts/gen_fork_spine.py — do not hand-edit. -->",
        "",
        f"Base (merge-base): `{base[:12]}` · fork HEAD: `{fork_rev[:12]}` · "
        f"upstream: `{up_rev[:12]}`.",
        "",
        "Classes: **A** fork-only · **B** upstream-only · **C** converged · "
        "**D** real delta · **U** modified, absent upstream. "
        "State enum: `ported | delta-carried | refused | not-porting` "
        "(v1: all `not-porting`; the port workflow flips rows with manifest linkage).",
        "",
        f"Counts: {', '.join(f'{k}={counts.get(k, 0)}' for k in 'ABCDEU' if k != 'E')} "
        f"({len(rows)} classified surfaces).",
        "",
        "| Surface | Class | Fork rev | Fork hash | Upstream hash | State |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for r in rows:
        lines.append(
            f"| `{r['surface']}` | {r['class']} | {r['fork_rev'] or '—'} | "
            f"{r['fork_hash'] or '—'} | {r['upstream_hash'] or '—'} | {r['state']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--fork", default=str(DEFAULT_FORK))
    ap.add_argument("--upstream", default=str(ROOT / "sources" / "firstmate"))
    ap.add_argument("--fork-rev", default=None)
    ap.add_argument("--base", default=None)
    args = ap.parse_args()
    fork, upstream = Path(args.fork), Path(args.upstream)
    try:
        fork_rev = args.fork_rev or sh(fork, "rev-parse", "HEAD").stdout.decode().strip()
        up_rev = sh(upstream, "rev-parse", "HEAD").stdout.decode().strip()
        # Default base is the recorded fork point (upstream #2091): the fork
        # repo does not carry current upstream objects, so no live merge-base
        # across repos is possible. Whatever base is used must resolve in the
        # fork store AND be an ancestor of the fork rev.
        base = args.base or "53ecbc7961ac066461ea3104c713d81d40fb32d6"
        sh(fork, "cat-file", "-t", base)
        sh(fork, "merge-base", "--is-ancestor", base, fork_rev)
    except subprocess.CalledProcessError as exc:
        print(f"gen_fork_spine: git resolution failed: {exc}", file=sys.stderr)
        return 2
    rows = derive(fork, fork_rev, upstream, up_rev, base)
    payload = {"base_rev": base, "fork_rev": fork_rev, "upstream_rev": up_rev,
               "rows": rows}
    md = render_md(rows, base, fork_rev, up_rev)
    if args.check:
        ok = True
        if not CHANGES_MD.is_file() or CHANGES_MD.read_text() != md:
            print("gen_fork_spine: manifest/CHANGES.md is stale; regenerate", file=sys.stderr)
            ok = False
        if not SPINE_JSON.is_file() or json.loads(SPINE_JSON.read_text()) != payload:
            print("gen_fork_spine: drift/fork-spine.json is stale; regenerate", file=sys.stderr)
            ok = False
        return 0 if ok else 1
    CHANGES_MD.write_text(md)
    SPINE_JSON.write_text(json.dumps(payload, indent=2) + "\n")
    counts: dict[str, int] = {}
    for r in rows:
        counts[r["class"]] = counts.get(r["class"], 0) + 1
    print(f"gen_fork_spine: {len(rows)} rows {counts} "
          f"(base {base[:12]} fork {fork_rev[:12]} upstream {up_rev[:12]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
