#!/usr/bin/env python3
"""Generate manifest/PARITY.md: the Kun parity report (bead project-2od.1).

The captain's standing order: bring firstmate_mcp to code/feature parity with
Kun's firstmate, with **our** changes pinned and reported as implemented-or-not.
Priority is explicit — upstream being current matters more than our additions
existing; ours need a pin and a verdict, not an implementation.

This assembles that report from the artifacts that already own each fact rather
than re-deriving them:

  - manifest/COVERAGE.md        per-command mirror status (mirrored / denied-by-design / gap)
  - manifest/FEATURES.yaml      per-feature kind, py/ts status, divergence status
  - schema/contracts.index.json the surface -> owning-script map
  - an optional --fm-home       which contracts that home can actually run

Usage:
    python3 scripts/gen_parity.py [-o manifest/PARITY.md] [--fm-home PATH]
    python3 scripts/gen_parity.py --check --fm-home PATH   # fail if the report is stale
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
COVERAGE = ROOT / "manifest" / "COVERAGE.md"
FEATURES = ROOT / "manifest" / "FEATURES.yaml"
INDEX = ROOT / "schema" / "contracts.index.json"
DEFAULT_OUT = ROOT / "manifest" / "PARITY.md"


def parse_coverage() -> list[dict]:
    """Per-command rows from the coverage view (the view owns the classification)."""
    rows = []
    for line in COVERAGE.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^\|\s*`([^`]+)`([^|]*)\|\s*([^|]+?)\s*\|\s*(.*?)\s*\|\s*$", line)
        if not m:
            continue
        command, extra, status, note = m.group(1), m.group(2).strip(), m.group(3).strip(), m.group(4)
        if status.startswith("mirrored"):
            kind = "mirrored"
        elif status.startswith("denied-by-design"):
            kind = "denied"
        elif status == "gap":
            kind = "gap"
        else:
            kind = "other"
        rows.append({"command": command, "extra": extra, "kind": kind, "status": status, "note": note})
    return rows


def parse_features() -> list[dict]:
    data = yaml.safe_load(FEATURES.read_text(encoding="utf-8"))
    return data.get("features", [])


def surface_commands() -> dict:
    if not INDEX.exists():
        return {}
    return json.loads(INDEX.read_text(encoding="utf-8")).get("contracts", {})


def served_line_report(fm_home: str | None) -> dict | None:
    """Which declared contracts this home can actually run."""
    commands = surface_commands()
    if not commands or fm_home is None:
        return None
    bin_dir = Path(fm_home) / "bin"
    if not bin_dir.is_dir():
        return {"error": f"no bin/ under {fm_home}"}
    dead = sorted(surface for surface, command in commands.items() if not (bin_dir / Path(command).name).exists())
    return {
        "home": fm_home,
        "total": len(commands),
        "resolvable": len(commands) - len(dead),
        "dead": dead,
    }


def build(fm_home: str | None) -> str:
    rows = parse_coverage()
    features = parse_features()
    mirrored = [r for r in rows if r["kind"] == "mirrored"]
    denied = [r for r in rows if r["kind"] == "denied"]
    gaps = [r for r in rows if r["kind"] == "gap"]
    removed = [r for r in gaps if "removed upstream" in r["extra"] or "removed upstream" in r["note"]]
    buildable = [r for r in gaps if r not in removed]

    kinds: dict[str, int] = {}
    ts_status: dict[str, int] = {}
    divergences: dict[str, int] = {}
    for feature in features:
        kinds[feature.get("kind", "?")] = kinds.get(feature.get("kind", "?"), 0) + 1
        ts_status[(feature.get("ts") or {}).get("status", "?")] = (
            ts_status.get((feature.get("ts") or {}).get("status", "?"), 0) + 1
        )
        status = (feature.get("divergence") or {}).get("status", "none")
        divergences[status] = divergences.get(status, 0) + 1

    out = []
    out.append("# Kun parity report\n")
    out.append(
        "Generated by `scripts/gen_parity.py` from `manifest/COVERAGE.md`, "
        "`manifest/FEATURES.yaml` and the contract index. Bead: `project-2od.1` "
        "(standing order — upstream current matters more than our additions; ours are "
        "pinned and reported, not reimplemented).\n"
    )

    out.append("## Surface parity: every current upstream command is classified\n")
    out.append(f"- upstream command surfaces enumerated: **{len(rows)}**")
    out.append(f"- mirrored: **{len(mirrored)}**")
    out.append(f"- denied-by-design: **{len(denied)}** (deliberate refusals, each with a reason in COVERAGE.md)")
    out.append(f"- gap rows: **{len(gaps)}** — of which removed-upstream **{len(removed)}**, current-upstream **{len(buildable)}**")
    if not buildable:
        out.append(
            "\n**No buildable gap remains**: every command the pinned upstream still ships is "
            "either mirrored through a tool or refused by design. The gap rows are commands "
            "upstream itself removed since the pin; they are history, not backlog.\n"
        )
    else:
        out.append("\nBuildable gaps:\n")
        for row in buildable:
            out.append(f"- `{row['command']}` — {row['note']}")
        out.append("")

    out.append("## Capability parity is deliberately partial\n")
    out.append(
        "Mirror parity is not capability parity: the denied-by-design set is the point of the "
        "doorway, not a shortfall. Denied surfaces by area (reason for each in COVERAGE.md):\n"
    )
    areas = {}
    current_area = None
    for line in COVERAGE.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            current_area = line[3:].strip()
        elif current_area and line.startswith("| ") and not line.startswith("| Command") and "denied-by-design" in line:
            areas[current_area] = areas.get(current_area, 0) + 1
    for area, count in sorted(areas.items(), key=lambda kv: -kv[1]):
        out.append(f"- {area}: {count}")
    out.append("")

    out.append("## Our changes: pinned and reported, not implemented\n")
    out.append(f"- features in `manifest/FEATURES.yaml`: **{len(features)}**")
    for kind, count in sorted(kinds.items(), key=lambda kv: -kv[1]):
        out.append(f"  - kind `{kind}`: {count}")
    out.append("- TypeScript status: " + ", ".join(f"{k} {v}" for k, v in sorted(ts_status.items())))
    out.append("- divergence status: " + ", ".join(f"{k} {v}" for k, v in sorted(divergences.items())))
    out.append("")

    # The fork block carries two revs on purpose; a reader asking "what are we
    # pinned at" was previously unable to tell them apart (owner asked 2026-09-22).
    fork = (yaml.safe_load(FEATURES.read_text(encoding="utf-8")) or {}).get("fork") or {}
    out.append("## The fork line: proof basis vs the line the fleet runs\n")
    if fork:
        out.append(f"- proof basis (`proven_commit`): `{fork.get('proven_commit')}` ({fork.get('proven_date')})")
        out.append(f"- served line (`served_commit`): `{fork.get('served_commit')}` ({fork.get('served_date')})")
        out.append(
            "\nThey are different revs: the proof basis is when CUTOVER-PROOF.md and "
            "UPSTREAM-RESULTS.md were produced; the served line is what `FM_HOME` actually "
            "runs. `manifest/validate.py` fails loudly if the served line and "
            "`drift/baseline.json` disagree, and `schema/validate.py` fails if the two "
            "files state different served revs. Keeping the fleet on a current line is "
            "operational (`project-2od.13`), not a doorway concern.\n"
        )
    else:
        out.append("(no fork provenance block found)\n")

    served = served_line_report(fm_home)
    out.append("## Served-line parity (the dimension surface parity does not cover)\n")
    if served is None:
        out.append("Run with `--fm-home PATH` to report which declared contracts that home can run.\n")
    elif "error" in served:
        out.append(f"{served['error']}\n")
    else:
        out.append(
            f"Home `{served['home']}`: **{served['resolvable']} of {served['total']}** declared "
            f"contracts have an owning script; **{len(served['dead'])}** do not, so the doorway "
            "mirrors those surfaces and this home cannot run them. Each refuses with "
            "`unavailable on this home` naming the script, and `doctor` reports the count live.\n"
        )
        out.append("Contracts with no implementation on that home:\n")
        for surface in served["dead"]:
            out.append(f"- `{surface}`")
        out.append("")
        out.append(
            "That is the shape gap tracked as `project-4sh` (map where the line has an "
            "equivalent, degrade legibly otherwise) — not a mirroring gap, and not something "
            "to fix by importing upstream scripts into the served line unasked.\n"
        )
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", default=str(DEFAULT_OUT))
    parser.add_argument("--fm-home", default=os.environ.get("FM_HOME"))
    parser.add_argument("--check", action="store_true", help="fail if the report on disk is stale")
    args = parser.parse_args(argv)

    rendered = build(args.fm_home)
    if args.check:
        target = Path(args.output)
        try:
            current = target.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"parity report: missing {target}: {exc}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                "parity report: manifest/PARITY.md is stale; run python3 scripts/gen_parity.py",
                file=sys.stderr,
            )
            return 1
        print("parity report: ok: manifest/PARITY.md is current")
        return 0
    Path(args.output).write_text(rendered, encoding="utf-8")
    print(f"parity report: wrote {Path(args.output).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
