#!/usr/bin/env python3
"""Generate schema/contracts.index.json: the surface -> owning script map.

Two partial sources had to be unioned, because neither alone can see the whole
surface:

- `schema/matrix.md` is a human view covering only the depended-on subset, so the
decision family is invisible in it (fm-captain-hold.sh has no matrix row).
- `schema/contracts.yaml` declares `bin/<script>` for 64 contracts, but the
decision tools point their contract at TS source instead, so they are absent
there too.
- `manifest/FEATURES.yaml` carries `upstream_command` for every mirrored feature,
  which is where the decision family and the other doorway-native wrappers are
  actually declared.

So the index is the union of both, dependency-free at runtime (the server reads
JSON; it has no YAML parser), and gated so it cannot go stale.

Usage:
    python3 scripts/gen_contract_index.py            # write the index
    python3 scripts/gen_contract_index.py --check    # fail if the index is stale
"""
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "schema" / "contracts.yaml"
FEATURES = ROOT / "manifest" / "FEATURES.yaml"
INDEX = ROOT / "schema" / "contracts.index.json"
VERSION = 1


def build() -> dict:
    contracts: dict[str, str] = {}

    # 1. Declared contracts: the depended-on declaration owns the answer.
    data = yaml.safe_load(CONTRACTS.read_text(encoding="utf-8"))
    for entry in data.get("contracts", []):
        name = entry.get("name")
        command = entry.get("command", "")
        # Only bin/<script> contracts own a script. Native stores ("native: ...")
        # and published files ("file: ...") have nothing to resolve on a home.
        if isinstance(name, str) and command.startswith("bin/"):
            contracts[name] = command

    # 2. Mirrored features: catches wrappers whose contract is the TS source.
    features = yaml.safe_load(FEATURES.read_text(encoding="utf-8"))
    for feature in features.get("features", []):
        name = feature.get("id")
        command = feature.get("upstream_command", "")
        if isinstance(name, str) and command.startswith("bin/") and name not in contracts:
            contracts[name] = command

    return {
        "version": VERSION,
        "sources": ["schema/contracts.yaml", "manifest/FEATURES.yaml"],
        "note": "Generated by scripts/gen_contract_index.py; do not edit by hand.",
        "contracts": dict(sorted(contracts.items())),
    }


def main(argv: list[str]) -> int:
    rendered = json.dumps(build(), indent=2) + "\n"
    if "--check" in argv:
        try:
            current = INDEX.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"contract index: missing {INDEX}: {exc}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                "contract index: schema/contracts.index.json is stale; "
                "run python3 scripts/gen_contract_index.py",
                file=sys.stderr,
            )
            return 1
        count = len(json.loads(current)["contracts"])
        print(f"contract index: ok: {count} bin/ contract(s) agree with contracts.yaml")
        return 0
    INDEX.write_text(rendered, encoding="utf-8")
    count = len(json.loads(rendered)["contracts"])
    print(f"contract index: wrote {count} bin/ contract(s) -> {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
